Talia/src/main/java/org/D7noun/model/Attachment.java
package org.D7noun.model;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;

import org.D7noun.model.File.AttachmentType;

@NamedQueries({
		@NamedQuery(name = Attachment.getAttacmentsById, query = "SELECT attach FROM Attachment attach where attach.file.id = ?1 ORDER BY attach.size asc"),
		@NamedQuery(name = Attachment.findById, query = "SELECT attach FROM Attachment attach WHERE attach.id = ?1") })
@Entity
public class Attachment implements Serializable {

	public static final String getAttacmentsById = "Attachment.getAttacmentsById";
	public static final String findById = "Attachment.findById";

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE)
	@Column(name = "id", updatable = false, nullable = false)
	private Long id;

	private String fileName;
	private String contentType;
	@Enumerated(EnumType.STRING)
	private AttachmentType attachmentType;
	private long size;
	private String notes;

	@Lob
	private byte[] data;

	/////////////
	@ManyToOne
	private File file;

	/**
	 * @return the id
	 */
	public Long getId() {
		return id;
	}

	/**
	 * @param id
	 *            the id to set
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * @return the fileName
	 */
	public String getFileName() {
		return fileName;
	}

	/**
	 * @param fileName
	 *            the fileName to set
	 */
	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	/**
	 * @return the contentType
	 */
	public String getContentType() {
		return contentType;
	}

	/**
	 * @param contentType
	 *            the contentType to set
	 */
	public void setContentType(String contentType) {
		this.contentType = contentType;
	}

	/**
	 * @return the size
	 */
	public long getSize() {
		return size;
	}

	public String getSizeInMegaByte() {
		long fraction = 1024;
		double sizeDouble = size;
		if (size != 0) {
			double sizeFraction = sizeDouble / fraction;
			sizeFraction = Math.floor(sizeFraction * 100) / 100;
			return sizeFraction + " KB";
		}
		return "0 MB";
	}

	/**
	 * @param size
	 *            the size to set
	 */
	public void setSize(long size) {
		this.size = size;
	}

	/**
	 * @return the data
	 */
	public byte[] getData() {
		return data;
	}

	/**
	 * @param data
	 *            the data to set
	 */
	public void setData(byte[] data) {
		this.data = data;
	}

	/**
	 * @return the serialversionuid
	 */
	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	/**
	 * @return the notes
	 */
	public String getNotes() {
		return notes;
	}

	/**
	 * @param notes
	 *            the notes to set
	 */
	public void setNotes(String notes) {
		this.notes = notes;
	}

	/**
	 * @return the file
	 */
	public File getFile() {
		return file;
	}

	/**
	 * @param file
	 *            the file to set
	 */
	public void setFile(File file) {
		this.file = file;
	}

	/**
	 * @return the attachmentType
	 */
	public AttachmentType getAttachmentType() {
		return attachmentType;
	}

	/**
	 * @param attachmentType
	 *            the attachmentType to set
	 */
	public void setAttachmentType(AttachmentType attachmentType) {
		this.attachmentType = attachmentType;
	}

}

Talia/src/main/java/org/D7noun/model/Belonging.java
package org.D7noun.model;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;

import org.D7noun.model.File.BelongingBenifit;
import org.D7noun.model.File.BelongingType;

@Entity
public class Belonging implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE)
	@Column(name = "id", updatable = false, nullable = false)
	private Long id;

	@Enumerated(EnumType.STRING)
	private BelongingType type;

	private String value;

	@Enumerated(EnumType.STRING)
	private BelongingBenifit benifit;

	private String notes;

	@ManyToOne
	private File file;

	/**
	 * @return the id
	 */
	public Long getId() {
		return id;
	}

	/**
	 * @param id
	 *            the id to set
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * @return the type
	 */
	public BelongingType getType() {
		return type;
	}

	/**
	 * @param type
	 *            the type to set
	 */
	public void setType(BelongingType type) {
		this.type = type;
	}

	/**
	 * @return the value
	 */
	public String getValue() {
		return value;
	}

	/**
	 * @param value
	 *            the value to set
	 */
	public void setValue(String value) {
		this.value = value;
	}

	/**
	 * @return the benifit
	 */
	public BelongingBenifit getBenifit() {
		return benifit;
	}

	/**
	 * @param benifit
	 *            the benifit to set
	 */
	public void setBenifit(BelongingBenifit benifit) {
		this.benifit = benifit;
	}

	/**
	 * @return the notes
	 */
	public String getNotes() {
		return notes;
	}

	/**
	 * @param notes
	 *            the notes to set
	 */
	public void setNotes(String notes) {
		this.notes = notes;
	}

	/**
	 * @return the file
	 */
	public File getFile() {
		return file;
	}

	/**
	 * @param file
	 *            the file to set
	 */
	public void setFile(File file) {
		this.file = file;
	}

	/**
	 * @return the serialversionuid
	 */
	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((benifit == null) ? 0 : benifit.hashCode());
		result = prime * result + ((file == null) ? 0 : file.hashCode());
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result + ((notes == null) ? 0 : notes.hashCode());
		result = prime * result + ((type == null) ? 0 : type.hashCode());
		result = prime * result + ((value == null) ? 0 : value.hashCode());
		return result;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Belonging other = (Belonging) obj;
		if (benifit != other.benifit)
			return false;
		if (file == null) {
			if (other.file != null)
				return false;
		} else if (!file.equals(other.file))
			return false;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (notes == null) {
			if (other.notes != null)
				return false;
		} else if (!notes.equals(other.notes))
			return false;
		if (type != other.type)
			return false;
		if (value == null) {
			if (other.value != null)
				return false;
		} else if (!value.equals(other.value))
			return false;
		return true;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "Belonging [id=" + id + ", type=" + type + ", value=" + value + ", benifit=" + benifit + ", notes="
				+ notes + ", file=" + file + "]";
	}

}

Talia/src/main/java/org/D7noun/model/EducationalPeople.java
package org.D7noun.model;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.D7noun.model.File.SchoolType;

@Entity
public class EducationalPeople implements Serializable {

	/**
	 * 
	 */

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE)
	@Column(name = "id", updatable = false, nullable = false)
	private Long id;

	private String name;
	@Temporal(TemporalType.DATE)
	private Date dateOfBirth;

	private String school;
	private String className;

	@Enumerated(EnumType.STRING)
	private SchoolType schoolType;

	private double annualPayment;

	private String partyHelpingName;
	private double partyHelpingContribution;

	@ManyToOne
	private File file;

	/**
	 * @return the name
	 */
	public String getName() {
		return name;
	}

	/**
	 * @param name
	 *            the name to set
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * @return the dateOfBirth
	 */
	public Date getDateOfBirth() {
		return dateOfBirth;
	}

	/**
	 * @param dateOfBirth
	 *            the dateOfBirth to set
	 */
	public void setDateOfBirth(Date dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	/**
	 * @return the school
	 */
	public String getSchool() {
		return school;
	}

	/**
	 * @param school
	 *            the school to set
	 */
	public void setSchool(String school) {
		this.school = school;
	}

	/**
	 * @return the className
	 */
	public String getClassName() {
		return className;
	}

	/**
	 * @param className
	 *            the className to set
	 */
	public void setClassName(String className) {
		this.className = className;
	}

	/**
	 * @return the schoolType
	 */
	public SchoolType getSchoolType() {
		return schoolType;
	}

	/**
	 * @param schoolType
	 *            the schoolType to set
	 */
	public void setSchoolType(SchoolType schoolType) {
		this.schoolType = schoolType;
	}

	/**
	 * @return the annualPayment
	 */
	public double getAnnualPayment() {
		return annualPayment;
	}

	/**
	 * @param annualPayment
	 *            the annualPayment to set
	 */
	public void setAnnualPayment(double annualPayment) {
		this.annualPayment = annualPayment;
	}

	/**
	 * @return the partyHelpingName
	 */
	public String getPartyHelpingName() {
		return partyHelpingName;
	}

	/**
	 * @param partyHelpingName
	 *            the partyHelpingName to set
	 */
	public void setPartyHelpingName(String partyHelpingName) {
		this.partyHelpingName = partyHelpingName;
	}

	/**
	 * @return the partyHelpingContribution
	 */
	public double getPartyHelpingContribution() {
		return partyHelpingContribution;
	}

	/**
	 * @param partyHelpingContribution
	 *            the partyHelpingContribution to set
	 */
	public void setPartyHelpingContribution(double partyHelpingContribution) {
		this.partyHelpingContribution = partyHelpingContribution;
	}

	/**
	 * @return the file
	 */
	public File getFile() {
		return file;
	}

	/**
	 * @param file
	 *            the file to set
	 */
	public void setFile(File file) {
		this.file = file;
	}

	/**
	 * @return the serialversionuid
	 */
	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		long temp;
		temp = Double.doubleToLongBits(annualPayment);
		result = prime * result + (int) (temp ^ (temp >>> 32));
		result = prime * result + ((className == null) ? 0 : className.hashCode());
		result = prime * result + ((dateOfBirth == null) ? 0 : dateOfBirth.hashCode());
		result = prime * result + ((file == null) ? 0 : file.hashCode());
		result = prime * result + ((name == null) ? 0 : name.hashCode());
		temp = Double.doubleToLongBits(partyHelpingContribution);
		result = prime * result + (int) (temp ^ (temp >>> 32));
		result = prime * result + ((partyHelpingName == null) ? 0 : partyHelpingName.hashCode());
		result = prime * result + ((school == null) ? 0 : school.hashCode());
		result = prime * result + ((schoolType == null) ? 0 : schoolType.hashCode());
		return result;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		EducationalPeople other = (EducationalPeople) obj;
		if (Double.doubleToLongBits(annualPayment) != Double.doubleToLongBits(other.annualPayment))
			return false;
		if (className == null) {
			if (other.className != null)
				return false;
		} else if (!className.equals(other.className))
			return false;
		if (dateOfBirth == null) {
			if (other.dateOfBirth != null)
				return false;
		} else if (!dateOfBirth.equals(other.dateOfBirth))
			return false;
		if (file == null) {
			if (other.file != null)
				return false;
		} else if (!file.equals(other.file))
			return false;
		if (name == null) {
			if (other.name != null)
				return false;
		} else if (!name.equals(other.name))
			return false;
		if (Double.doubleToLongBits(partyHelpingContribution) != Double
				.doubleToLongBits(other.partyHelpingContribution))
			return false;
		if (partyHelpingName == null) {
			if (other.partyHelpingName != null)
				return false;
		} else if (!partyHelpingName.equals(other.partyHelpingName))
			return false;
		if (school == null) {
			if (other.school != null)
				return false;
		} else if (!school.equals(other.school))
			return false;
		if (schoolType != other.schoolType)
			return false;
		return true;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "EducationalPeople [name=" + name + ", dateOfBirth=" + dateOfBirth + ", school=" + school
				+ ", className=" + className + ", schoolType=" + schoolType + ", annualPayment=" + annualPayment
				+ ", partyHelpingName=" + partyHelpingName + ", partyHelpingContribution=" + partyHelpingContribution
				+ ", file=" + file + "]";
	}

	/**
	 * @return the id
	 */
	public Long getId() {
		return id;
	}

	/**
	 * @param id
	 *            the id to set
	 */
	public void setId(Long id) {
		this.id = id;
	}

}

Talia/src/main/webapp/resources/snippets/attachments.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:p="http://primefaces.org/ui">

<div class="row">
	<div class="col-md-12">
		<p:dataTable id="attachmentsDataTable" widgetVar="attachmentVar"
			rows="5" paginator="true"
			paginatorTemplate="{CurrentPageReport} {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
			rowsPerPageTemplate="5,10,15,20,50" paginatorAlwaysVisible="false"
			paginatorPosition="bottom" value="#{fileBean.file.attachments}"
			var="attachment" rowKey="#{attachment.id}" rowIndexVar="index"
			editable="true" editMode="cell" emptyMessage="#{app.empty_table}">

			<f:facet name="header">

				<h:outputText value="#{app.attachments}"
					styleClass="attachmentHeaderText" />

				<p:fileUpload widgetVar="fileUploadVar" multiple="true" auto="true"
					styleClass="fileUploader hide"
					fileUploadListener="#{fileBean.handleFileUpload}"
					process="@this attachmentsDataTable" update="attachmentsDataTable" />

				<h:commandLink onclick="$('.fileUploader input').click()"
					styleClass="btn btn-primary white attachmentHeaderButton">
					<f:ajax />
					<i class="fa fa-plus white" />
				</h:commandLink>

			</f:facet>

			<p:column id="index" width="50">
				<h:outputText value="#{index+1}"></h:outputText>
			</p:column>

			<p:column id="actions" width="50">
				<h:commandLink styleClass="btn btn-sm btn-danger white"
					action="#{fileBean.selectForDelete(attachment)}"
					onclick="PF('deleteAttachmentDialogVar').show()">
					<i class="fa fa-trash white" />
					<f:ajax />
				</h:commandLink>
			</p:column>

			<p:column id="attachmentName" headerText="#{app.attachmentName}"
				filterMatchMode="contains" filterBy="#{attachment.fileName}"
				sortBy="#{attachment.fileName}" styleClass="attachmentName-column"
				width="">
				<h:outputText value="#{attachment.fileName}"
					title="#{attachment.fileName}" />
			</p:column>

			<p:column id="attachmentSize" headerText="#{app.attachmentSize}"
				sortBy="#{attachment.size}" style="text-align: center">
				<h:outputText value="#{attachment.sizeInMegaByte}"
					title="#{attachment.sizeInMegaByte}" />
			</p:column>

			<p:column id="attachmentType" headerText="#{app.attachmentType}"
				filterMatchMode="contains" filterBy="#{attachment.attachmentType}"
				sortBy="#{attachment.attachmentType}"
				styleClass="attachmentType-column">
				<p:selectOneMenu value="#{attachment.attachmentType}">
					<f:selectItem />
					<f:selectItem itemLabel="#{app.DeadPaper}" itemValue="Dead" />
					<f:selectItem itemLabel="#{app.Divorce}" itemValue="Divorce" />
					<f:selectItem itemLabel="#{app.Family}" itemValue="Family" />
					<f:selectItem itemLabel="#{app.FirstBenefit}"
						itemValue="FirstBenefit" />
					<f:selectItem itemLabel="#{app.Husband}" itemValue="Husband" />
					<f:selectItem itemLabel="#{app.Medical}" itemValue="Medical" />
					<f:selectItem itemLabel="#{app.Medicine}" itemValue="Medicine" />
				</p:selectOneMenu>
			</p:column>

			<p:column id="notes" headerText="Notes" filterMatchMode="contains"
				filterBy="#{attachment.notes}" sortBy="#{attachment.notes}"
				styleClass="attachmentNotes-column">
				<h:inputText value="#{attachment.notes}" styleClass="form-control" />
			</p:column>

			<p:column width="50">
				<h:commandLink action="#{fileBean.download(attachment)}"
					styleClass="btn btn-sm btn-primary">
					<i class="fa fa-download white" />
				</h:commandLink>

			</p:column>

		</p:dataTable>
	</div>
</div>


<p:dialog id="deleteAttachmentDialog" draggable="false" closable="false"
	modal="true" height="50" width="310" resizable="false"
	widgetVar="deleteAttachmentDialogVar">

	<f:facet name="header">
		<h:outputText value="Confirm Deletion????" />
	</f:facet>

	<h:commandLink value="Ok" action="#{fileBean.deleteAttachment()}"
		onclick="PF('deleteAttachmentDialogVar').hide()"
		styleClass="btn btn-sm btn-primary popup-buttons">
		<f:ajax render="attachmentsDataTable" />
	</h:commandLink>
	<h:commandLink value="Cancel"
		styleClass="btn btn-sm btn-danger popup-buttons"
		onclick="PF('deleteAttachmentDialogVar').hide()">
		<f:ajax />
	</h:commandLink>
</p:dialog>

</html>

Talia/src/main/webapp/resources/snippets/income.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:p="http://primefaces.org/ui">



<div class="row">
	<div class="col-md-12">

		<p:dataTable id="familyIncomesDataTable" rows="7" paginator="false"
			widgetVar="familyIncomesDataTableVar"
			value="#{fileBean.file.familyIncomes}" var="item" rowKey="#{item.id}"
			rowIndexVar="index" emptyMessage="#{app.empty_table}">

			<f:facet name="header">
				<h:outputText value="#{app.familyIncomes}" styleClass="headerText" />
			</f:facet>

			<p:column id="index" width="50">
				<h:outputText value="#{index+1}"></h:outputText>
			</p:column>

			<p:column id="edit" width="50">
				<h:commandLink styleClass="btn btn-sm btn-success white"
					action="#{fileBean.openEditFamilyIncomeDialog(item)}">
					<i class="fa fa-pencil white" />
					<p:ajax update="editFamilyIncomeDialog"
						oncomplete="PF('editFamilyIncomeDialogVar').show()" />
				</h:commandLink>
			</p:column>

			<p:column id="FamilyIncomesource"
				headerText="#{app.FamilyIncomesource}" filterBy="#{item.source}"
				filterMatchMode="contains" sortBy="#{item.source}">
				<h:outputText value="#{item.source}" title="#{item.source}" />
			</p:column>

			<p:column id="FamilyIncomevalue"
				headerText="#{app.FamilyIncomevalue}" filterBy="#{item.value}"
				filterMatchMode="contains" sortBy="#{item.value}">
				<h:outputText value="#{item.value}" title="#{item.value}" />
			</p:column>

			<p:column id="FamilyIncomeduration"
				headerText="#{app.FamilyIncomeduration}" filterBy="#{item.duration}"
				filterMatchMode="contains" sortBy="#{item.duration}">
				<h:outputText value="#{item.duration}" title="#{item.duration}" />
			</p:column>

			<p:column id="FamilyIncomenotes"
				headerText="#{app.FamilyIncomenotes}" filterBy="#{item.notes}"
				filterMatchMode="contains" sortBy="#{item.notes}">
				<h:outputText value="#{item.notes}" title="#{item.notes}" />
			</p:column>

			<p:columnGroup type="footer">
				<p:row>
					<p:column />
					<p:column />
					<p:column />
					<p:column footerText="#{fileBean.incomeSum()}" />
					<p:column />
					<p:column />
				</p:row>
			</p:columnGroup>

		</p:dataTable>

		<p:dialog id="editFamilyIncomeDialog"
			widgetVar="editFamilyIncomeDialogVar" closable="true"
			showHeader="false" showEffect="clip" hideEffect="clip"
			draggable="false" maximizable="false" modal="true" width="800"
			height="350" resizable="false" styleClass="addDialog"
			onShow="updateComponents()">

			<div class="row">
				<div class="col-md-12">
					<div class="form-group">

						<div class="col-md-12">
							<div class="col-md-4">
								<h:outputLabel styleClass="control-label"
									value="#{app.FamilyIncomesource}" />
							</div>
							<div class="col-md-8">
								<h:inputText readonly="true" styleClass="form-control"
									value="#{fileBean.editFamilyIncome.source}" />
							</div>
						</div>

						<div class="col-md-12">
							<div class="col-md-4">
								<h:outputLabel styleClass="control-label"
									value="#{app.FamilyIncomevalue}" />
							</div>
							<div class="col-md-8">
								<p:inputNumber inputStyleClass="form-control"
									value="#{fileBean.editFamilyIncome.value}" styleClass="money"
									symbol="$" symbolPosition="s" decimalSeparator="."
									thousandSeparator="," minValue="0" />
							</div>
						</div>

						<div class="col-md-12">
							<div class="col-md-4">
								<h:outputLabel styleClass="control-label"
									value="#{app.FamilyIncomeduration}" />
							</div>
							<div class="col-md-8">
								<h:inputText styleClass="form-control"
									value="#{fileBean.editFamilyIncome.duration}" />
							</div>
						</div>

						<div class="col-md-12">
							<div class="col-md-4">
								<h:outputLabel styleClass="control-label"
									value="#{app.FamilyIncomenotes}" />
							</div>
							<div class="col-md-8">
								<h:inputText styleClass="form-control"
									value="#{fileBean.editFamilyIncome.notes}" />
							</div>
						</div>

					</div>
				</div>

			</div>

			<f:facet name="footer">

				<h:commandLink value="#{app.ok}"
					styleClass="btn btn-primary popup-buttons"
					onclick="PF('editFamilyIncomeDialogVar').hide()">
					<p:ajax process="editFamilyIncomeDialog"
						update="familyIncomesDataTable"
						oncomplete="PF('familyIncomesDataTableVar').filter()" />
				</h:commandLink>

				<h:commandLink styleClass="btn btn-danger popup-buttons"
					onclick="PF('editFamilyIncomeDialogVar').hide()">
					<h:outputText value="#{app.cancel}" />
					<f:ajax />
				</h:commandLink>
			</f:facet>

		</p:dialog>

	</div>
</div>

</html>

Talia/src/main/webapp/resources/snippets/notes.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:p="http://primefaces.org/ui">

<!-- Notes -->

<div class="form-group">
	<div class="col-md-12">
		<div class="col-md-3">
			<h:outputLabel styleClass="control-label" for="socialSectionNotes"
				value="#{app.socialSectionNotes}:" />
		</div>
		<div class="col-md-9">
			<p:inputTextarea id="socialSectionNotes" styleClass="form-control"
				value="#{fileBean.file.socialSectionNotes}" />
			<h:message for="socialSectionNotes" styleClass="error" />
		</div>
	</div>
</div>

</html>